### ISSUE TITLE
Book site not working

### ISSUE THREAD

**Issue by meblum** [JonPSmith/EfCoreInAction#10]
Trying to access [http://efcoreinaction.com/](url) , it seems to be down.
![Annotation 2019-12-10 125208](https://user-images.githubusercontent.com/33358938/70554867-f4190900-1b4b-11ea-8cd8-f7078d6d992f.jpg)

**Comment by JonPSmith** [comment]
Yes, I'll try again later. Not sure what it is.

**Comment by JonPSmith** [comment]
Wow, The code was uploaded when I was working on NET Core 1 - its been running all that time. My host provider has removed NET Core 1 so I need to update the code. I'll do that when I have time as I have lot going on at the moment.

**Comment by meblum** [comment]
Btw Jon, your book is amazing. I'm up to chapter 6 and it's just a pleasure
to read! It's not just another book "to do this, do that", but full of
advanced techniques, design patterns, good practices, and all written in a
professional way, to the point, but still easy to understand. I think it's
one of the best technical book I've ever read. I also really enjoy the
blog. This is not related to the issue, but letting you know I really
appreciate it. 👍👍😀

**Comment by JonPSmith** [comment]
That is really nice to hear - thank you so much. The book took a lot of work, but I tried make it useful to developers. I was pleased with the end result, but hearing from a real reader that it was useful is really nice to hear. It also comes at the end of a long, hard day on a client's application, which is nice. 😀

**Comment by Allann** [comment]
> Btw Jon, your book is amazing. I'm up to chapter 6 and it's just a pleasure to read! It's not just another book "to do this, do that", but full of advanced techniques, design patterns, good practices, and all written in a professional way, to the point, but still easy to understand. I think it's one of the best technical book I've ever read. I also really enjoy the blog. This is not related to the issue, but letting you know I really appreciate it. 👍👍😀


I second that.

**Comment by mbbrennan** [comment]
I agree. Really good EF book.

**Comment by JonPSmith** [comment]
Thanks all. I'm glad you found it useful.

I have just finished writing the 2nd edition of [the book](https://bit.ly/EfCoreBookEd2), which covers EF Core 5. It also has lots of new content, with an extra 100 pages.

Note: as of today (Christmas 2020) only the first 10 chapters out. The other chapters I won't be out for a month or two as they go though a very rigorous series of reviews and updates before they are lot out.
