### ISSUE TITLE
Confusing about the book content page 84

### ISSUE THREAD

**Issue by LeTranAnhVu** [JonPSmith/EfCoreInAction#12]
Hi Jon,
I love your book and the way that you explained is easy to me to understand. However, there is a concern I still need to confirm. In the page 84 of the book, there is a sentence : 
`Also, the Find method isn’t affected by a model-level filter.` 

So what you means is we can actually get the soft-deleted item by using Find method? Can you share any resource that mentioned about it? 

Thank you very much.

**Comment by JonPSmith** [comment]
Hi @LeTranAnhVu 

That's a mistake! Sorry about that. The Query Filters are very secure and `Find` doesn't break that. Sorry about that. You can find a [unit test on Query filter](https://github.com/JonPSmith/EfCoreinAction-SecondEdition/blob/master/Test/UnitTests/TestDataLayer/Ch06_QueryFilters.cs) in the repo for the 2nd edition of my book. 

You might like my article [EF Core In depth – Soft deleting data with Global Query Filters](https://www.thereformedprogrammer.net/ef-core-in-depth-soft-deleting-data-with-global-query-filters/) which digs into the Query Filter in more depth.
