### ISSUE TITLE
Is checking !db.Books.Any() necessary after EnsureDeleted followed by EnsureCreated?

### ISSUE THREAD

**Issue by sadqiang** [JonPSmith/EfCoreInAction#4]
I am reading the chapter one right now. I found the `WipeCreateSeed` as follows:

```
db.Database.EnsureDeleted();
db.Database.EnsureCreated();
if (!db.Books.Any())
{
　　　WriteTestData(db);
　　　Console.WriteLine("Seeded database");
}
```

My question: Is `if (!db.Books.Any())` necessary here? We already have a brand new database before `if (!db.Books.Any())` so `!db.Books.Any()` always return true, IMHO.

**Comment by JonPSmith** [comment]
Hi @sadqiang,

Yep, that's not necessary. I don't show that code in the book though, which is a good thing. Thanks for pointing that out.
