### ISSUE TITLE
Upgrading this repo to .Net Core 3.0

### ISSUE THREAD

**Issue by npagare** [JonPSmith/EfCoreInAction#9]
Hi @JonPSmith , how are you?

Thank you for a wonderful book on the EF Core.

As EF Core 3.0 is GA now, will you be releasing -
1. A new edition of your book that refers to EF Core 3.0 and 
2. Updated version of this GitHub repo that works with EF Core 3.0 ?

Thank you.

**Comment by JonPSmith** [comment]
H @IoTFier,

At this time I'm not going to update the book or the GitHub repo to EF Core 3.0, but in the coming months I will be writing articles on my web site https://www.thereformedprogrammer.net/ about the parts that have changes.

EF Core 3.0 is a big change underneath, but very small changes to the interfaces ([see breaking changes](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes)). That means most of the book is still relevant. The two big changes are:
- Support for CosmosDb. I have already done one article on that and plan to do another one now 3.0 is out.
- Chapter 13, which is gives an example of tuning EF Core database performance, is out of date. I plan to write an article on that too.

At the moment I'm updating five of my open-source libraries to work with EF Core 3.0

**Comment by IoTFier** [comment]
Hi @JonPSmith, I appreciate your input.

Your guidance on these requests will be highly appreciated -

1. Is there a DBSet.AddOrUpdate in EF Core 3.0 that provided in EF 6.x ?
2. In my App, I am using .Net Core (3.0) to build my services layer and Sqlite database. I have opted for the DB first approach
•	created my db schema using Sqlitebrower utility 
•	generated scaffolding code using .Net EF Core CLI via PMC (package management console in VS 2019) 
•	using repository pattern to expose database APIs via my App Services to my ViewModels

Questions – 
   2.1>	Any recommendations for an utility to seed initial / test data from CSV files (that were exported from the Sqlitebroswer utility for each table) at the App bootstrap?
        It is easier for my business users to provide data in the .csv files (across db tables relationships).  The best (and only one) that I found so far is from David Paquette https://github.com/dpaquette/EntityFramework.Seeder but it is not ready to be used for .Net Core  yet

   2.2>	What are the best patterns and practices to plan for database backup restore throughout the application lifecyle of the Mobile App?.  Any pointers on blog or videos that talk about these needs ? 
         I can use migrations after the core entities are created / modified after database is updated / version managed via Sqlitebrower / GitHub etc. But, I’m looking for specific best practices to account for from the first installation to iterative upgrades of my App -  what & how to write db scripts that will backup / restore / load / modify data in the db to get new version of my SQLite DB functionally ready before user is hitting App. 

  2.3>	Any blogs / guidance on how to transition from SQLite DB to Cosmos DB based Restful resources, especially with the support of .EF Core 3.0 Cosmos DB provider, that modernize / replace my repository services written top of SQLite DB?

I would really appreciate your thoughts on this.

Thank you.

**Comment by JonPSmith** [comment]
That's a lot of questions, but I don't have any answers because each one is a major topic, especially database backup/restore. You will need to research each one yourself as I charge, and I'm not currently available as I have a full load with a client and trying to update libraries to NET Core 3.0

**Comment by npagare** [comment]
Thank you @JonPSmith. I have cleaned up those from this git hub issue.
